title: Correio Olindense
email: olindensecorreio@gmail.com
description: 'Blog de noticias de Olinda'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://correioolindense.com.br/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: correioolindense
github_username:  correioolindense
disqus: 'correioolindense'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Paginate
paginate: 24

authors:
    alexandre:
      name:           Alexandre Santos
      nickname:       Cabo Gato
      socialName:     alexandre
      site:           
      avatar:         assets/images/autor1.png
      bio:            "Olá, meu nome é Alexandre Cabo Gato, Minha jornada é desbravar os meandros da política local, revelando nuances e impactos que muitas vezes passam despercebidos. Com uma caneta afiada e uma busca incansável pela verdade, meu objetivo é oferecer uma visão abrangente e imparcial dos eventos que moldam nossa região. Acredito que uma sociedade bem informada é fundamental para o progresso, e estou comprometido em trazer notícias que capacitam e inspiram nossos leitores a participar ativamente do cenário político. Vamos explorar juntos as histórias que moldam nosso presente e futuro."
      email:          fakemail@gmail.com
      twitter:        https://x.com/alexandrespe?s=21
      instagram:      https://www.instagram.com/alexandrecabogato?igsh=NHhldXhyZDcwZDkx
      linkedin:

    elias:
      name:           Elias Barreto
      nickname:         
      socialName:     elias
      site:           
      avatar:         assets/images/autor2.jpg
      bio:            "Oi, sou Elias, um engenheiro de software apaixonado por tecnologia e dedicado à missão de aprimorar a sua experiência digital no nosso blog. Com um profundo compromisso com a inovação, trabalho incansavelmente nos bastidores, garantindo a eficiência e confiabilidade de nossa plataforma. Meu objetivo é proporcionar uma navegação intuitiva e recursos avançados que permitam aos leitores explorarem as nuances do cenário político local. Estou entusiasmado em contribuir para uma fonte de informações dinâmica e acessível, conectando comunidades por meio da tecnologia e da notícia."
      email:          elias-barreto@outlook.com
      twitter:        
      instagram:      https://www.instagram.com/eliasbarret?igsh=eTRhbTJvbWpnb3R2
      linkedin:       https://www.linkedin.com/in/ebff/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: alexandre
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page    

# Diz explicitamente ao Jekyll onde ficar o cache
cache_dir: .jekyll-cache

# plugins:
#   - jekyll-paginate
#   - jekyll-feed
#   - jekyll-sitemap
#   - jekyll-seo-tag
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - vendor
  - .bundle
  - tmp
  - scripts
  - README.md
  - package-lock.json
  - package.json
  - yarn.lock
  - README.markdown
  - grunt.js
  - Gruntfile.js
  - Gruntfile.coffee
  - _posts/2024/
  - assets/2024/
  - _posts/2025/janeiro/
  - assets/2025/janeiro/
  - _posts/2025/fevereiro/
  - assets/2025/fevereiro/
  - _posts/2025/marco/
  - assets/2025/marco/
  - _posts/2025/abril/
  - assets/2025/abril/
  - _posts/2025/maio/
  - assets/2025/maio/
  - _posts/2025/junho/
  - assets/2025/junho/

# Exclude metadata and development time dependencies (like Grunt plugins)
#exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
